server:
  port: 9033

spring:
  application:
    name: employee-skill-profile-service

  config:
    import: configserver:http://localhost:8888

  kafka:
    bootstrap-servers: localhost:9092

  cloud:

    # 🔵 CONFIG BUS (OK)
    bus:
      id: ${spring.application.name}:${server.port}
      enabled: true
      destination: springCloudBus

    # 🟡 STREAM (EVENT SYSTEM)
    stream:

      defaultBinder: kafka

      bindings:

        # 🔼 PRODUCER (send skill event)
        employeeSkillOutput-out-0:
          destination: employee-skill-events

        # 🔽 CONSUMER (receive approval event)
        approvalInput-in-0:
          destination: approval-events
          group: employee-skill-group

          consumer:
            maxAttempts: 3
            backOffInitialInterval: 1000
            backOffMultiplier: 2.0

      kafka:
        binder:
          brokers: localhost:9092

        bindings:

          approvalInput-in-0:
            consumer:
              enableDlq: true
              dlqName: approval-events.DLQ

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"